// Generated by Xata Codegen 0.26.7. Please do not edit.
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";
import { buildClient } from "@xata.io/client";

const tables = [
  {
    name: "job",
    columns: [
      { name: "location", type: "string" },
      { name: "company", type: "string" },
      { name: "title", type: "string" },
      { name: "type", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Job = InferredTypes["job"];
export type JobRecord = Job & XataRecord;

export type DatabaseSchema = {
  job: JobRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Tony-Ayala-s-workspace-tk4e6v.us-east-1.xata.sh/db/astro",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};

export const newXataClientWithViteEnv = () => {
  return new XataClient({ apiKey: import.meta.env.XATA_API_KEY, databaseURL: defaultOptions.databaseURL })
}